spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/orders}
    username: ${DB_USER:user}
    password: ${DB_PASS:pass}
  logging:
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: order-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
    properties:
      spring.json.trusted.packages: "*"

server:
  port: 8082

app:
  kafka:
    topics:
      order-created: order.created
      payment-completed: payment.completed
      payment-failed: payment.failed